apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: qtws
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: POC
          value: POC
        image: quay.io/redhat-appstudio-qe/byoc-jqhp-tenant/byoc-app-lmqs/qtws@sha256:d7958b349f05b6426aff4e0e3951a862067872ddebca29c738e7e97f4411a691
        name: my-java-quarkus
        resources: {}
status: {}
