apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: qtws
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qtws
    app.kubernetes.io/part-of: byoc-app-lmqs
  name: qtws
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: qtws
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: qtws
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-jqhp-tenant/byoc-app-lmqs/qtws@sha256:d7958b349f05b6426aff4e0e3951a862067872ddebca29c738e7e97f4411a691
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
