apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: qtws
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qtws
    app.kubernetes.io/part-of: byoc-app-lmqs
  name: qtws
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: qtws
status:
  loadBalancer: {}
